### PR TITLE
Finalize flows and design

### LINKED ISSUE #22: Finalize Flows and Design in Figma
### Description
Complete the design and user flows in **Figma**, ensuring all screens and interactions are well-defined and visually cohesive. The objective is to provide a clear guide for stakeholders and developers.

### Requirements
- **Flows:**
  - Clearly outline all user steps with arrows and annotations for transitions.
- **Screen Design:**
  - Finalize visuals for all screens, using placeholders or real content where needed.
- **Components:**
  - Create reusable components and include interaction states (hover, active, disabled).

### Technical Considerations
- Align designs with branding guidelines.

### Tasks
1. Review and refine existing designs in Figma.
2. Finalize user journey flows and screens.
3. Create reusable components with interaction states.
4. Prototype the flow to simulate interactions.
5. Upload a file with the link to Figma in the PR

### Notes
Focus on design and flow creation only; no implementation tasks are required.

### PR DESCRIPTION
**Pull request by od-hunter**
# Pull Request Overview

## 📝 Summary
Created design and user flow in Figma, ensuring all screens and interactions are well-defined and visually cohesive. The objective is to provide a clear guide for stakeholders and developers.

### 🔗 Related Issues
- Closes #22.

## 🔄 Changes Made
Please provide a general description of your changes. Include any relevant background information or context that may help reviewers understand the purpose of this PR.

## 🖼️ Current Output
Give evidence like screenshots of what your job looks like.

## 🧪 Testing
If applicable, describe the tests performed. Provide screenshots, test outputs, or any resources that can help reviewers understand how the changes were tested.

## 💬 Comments
Any additional context, questions, or considerations for the reviewers.

### CODE REVIEW

**Comment by od-hunter** [comment]
@MPSxDev , please review

**Review by MPSxDev — CHANGES_REQUESTED** [review]
Please rename it to DESIGN.md

**Comment by od-hunter** [comment]
Don! @MPSxDev , please review.

**Review by MPSxDev — APPROVED** [review]
Very good, thanks for the work

**Pull request merged**
